services:
  - type: web
    name: rising-waters
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT -w 4
    envVars:
      - key: PORT
        value: '10000'
